# Generated by Django 5.2.3 on 2025-06-10 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
