# Generated by Django 5.2.3 on 2025-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_alter_outreachpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpost',
            name='body',
            field=models.TextField(),
        ),
    ]
