# Generated by Django 5.2.3 on 2025-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_alter_outreachpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
