# Generated by Django 5.2.3 on 2025-08-24 16:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_alter_outreachpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
