# Generated by Django 5.2.3 on 2025-08-27 14:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_alter_outreachpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
