# Generated by Django 5.2.3 on 2025-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_projectembeddedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='project/images'),
        ),
    ]
