# Generated by Django 5.2.3 on 2025-08-25 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='honeypot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
